site_name: CouchDB Driver Library
theme: material
repo_url: https://github.com/MCStreetguy/cdb-driver
copyright: (c) 2018, Maximilian Schmidt
pages:
  - CDBDriver: index.md
  - Reference: reference.md
  - Further Information: misc.md
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
